#   ## Configura o Telegraf para se inscrever em tópicos MQTT e consumir mensagens.
 [[inputs.mqtt_consumer]]
#   ## Broker URLs for the MQTT server or cluster.  
   servers = ["tcp://127.0.0.1:1883"]
#   ## Topics that will be subscribed to.
   topics = [
     "rpiot/curso/+/+/+",
     "sensors/#"
   ]
#   ## The message topic will be stored in a tag specified by this value.  If set
#   ## to the empty string no topic tag will be created.
    topic_tag = "topic"
#   ## QoS policy for messages: 0 = at most once; 1 = at least once; 2 = exactly once
#   ## When using a QoS of 1 or 2, you should enable persistent_session to allow
#   ## resuming unacknowledged messages.
    qos = 0
#   ## Data format to consume.
    data_format = "json"
#   ## JSON strings and booleans are ignored unless specified here
    json_string_fields = ["stationId"]

[[inputs.mqtt_consumer.topic_parsing]]
  topic = "rpiot/curso/+/+/+"
  # O 5º campo (sensor) será o nome da 'measurement' no InfluxDB
  measurement = "_/_/_/_/measurement“
  # O 3º ('local') e 4º ('dispositivo') campos serão as tags
  tags = "_/_/local/dispositivo/_“
  # Pouco comum usar fields daqui, geralmente vêm do payload
  # fields = "_/_/_/_"
